name:                sturdy-tutorial
version:             0.3.0.0
license:             BSD3
maintainer:          Sven Keidel <svenkeidel@gmail.com>
category:            Language

dependencies:
  - base
  - hashable
  - mtl
  - profunctors
  - prettyprinter
  - sturdy-lib
  - sturdy-arrows
  - random
  - text
  - transformers
  - containers
  - unordered-containers

library:
  source-dirs:
    - src

  ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - sturdy-tutorial
