flags: {}
extra-package-dbs: []
resolver: lts-16.5
packages:
- 'arrows'
- 'lib'
- 'pcf'
- 'scheme'
- 'while'
- 'wasm'
# - 'stratego'
- 'jimple'
- 'tutorial'
allow-newer: true
extra-deps:
  - git: https://github.com/svenkeidel/dump-core/
    commit: 0c07091a7413cf808c2e01e2011589c1ed175667
  - monadLib-3.10
  - git: https://github.com/svenkeidel/husk-scheme/
    commit: ca59598b11065eb29a45af7ffca27fc42a49abe5
  - git: https://gitlab.rlp.net/plmz/external/haskell-wasm.git
    commit: 9e764fb16d7a1f44ce031f491b176096b9a799f4
  - knob-0.1.1
