flags: {}
extra-package-dbs: []
resolver: lts-13.30
packages:
- 'lib'
- 'pcf'
- 'while'
- 'wasm'
# - 'stratego'
# - 'jimple'
# - 'tutorial'
extra-deps:
  # - dump-core-0.1.3.2
  - monadLib-3.9
  - git: git@gitlab.rlp.net:plmz/external/haskell-wasm.git
    commit: 0ce9f9bdf705f6e0aa55e4ea4a0ac27b141ec80a
