name:                sturdy-stratego
version:             0.2.0.0
license:             BSD3
maintainer:          Sven Keidel <svenkeidel@gmail.com>
category:            Language

flags:
  case-studies:
    description: Enable case studies for stratego
    default:     False
    manual:      True

dependencies:
  - base
  - attoparsec
  - containers
  - deepseq
  - fgl
  - hashable
  - profunctors
  - mtl
  - sturdy-lib
  - text
  - transformers
  - unordered-containers
  - QuickCheck
  - hspec

  # - dump-core

data-files:
  - case-studies/arrows/arrows.aterm
  - case-studies/pcf/pcf.aterm
  - case-studies/arith/arith.aterm
  - case-studies/cca/cca.aterm
  - case-studies/go2js/go2js.aterm
  - case-studies/nnf/nnf.aterm
  - case-studies/balg/balg.aterm

library:
  source-dirs:
    - src
  ghc-options: -Wall # -fplugin=DumpCore -fplugin-opt DumpCore:core-html

executables:
  case-studies:
    source-dirs:
      - case-studies
    main: Main.hs
    dependencies:
      - sturdy-stratego
      - pretty
      - vector
      - criterion
    when:
      condition: flag(case-studies)
      then:
        buildable: true
      else:
        buildable: false

benchmarks:
  sort-semantics:
    source-dirs:
      - bench
    main: SortSemanticsBench.hs
    dependencies:
      - sturdy-stratego
      - criterion


tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - sturdy-stratego
