name:                sturdy-categories
version:             0.1.0.0
license:             BSD3
maintainer:          Sven Keidel <svenkeidel@gmail.com>
category:            Language

dependencies:
  - base
  - ghc

library:
  source-dirs:
    - src

  ghc-options: -Wall

tests:
  spec:
    main: Spec.hs

    source-dirs:
      - test

    ghc-options: -Wall -fplugin=Plugin.Categories

    dependencies:
      - sturdy-categories
      - hspec
